config/routes.rb
Rails.application.routes.draw do

  get 'supported_cities/index'

  get 'attraction_info/index'

  get 'import/index'

  resources :triplaces do
    collection {post :import}
  end
  resources :cities

  resources :schedules

  # cities api routes
  get 'data/cities'
  get 'data/city/:id', to: 'data#city'

  # attraction api routes
  get 'data/attraction/:id', to: 'data#attraction'

  # city page routes
  get 'city_detail/:id', to: 'city_detail#index'

  # attraction page routes
  get 'attraction_detail/:id', to: 'attraction_info#index'

  # generate schedule routes
  get 'generate_schedule/city/:city_id/days/:days', to: 'generate_schedule#no_budget'
  get 'generate_schedule/city/:city_id/days/:days/budget/:budget', to: 'generate_schedule#budget'

  # schedules routes
  get 'schedules/city/:city_id/days/:days/budget/:budget', to: 'schedules#index'
  get 'schedules/:id', to: 'schedules#show'

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'add', to: 'cities#new', as: 'add'
  get 'import', to: 'import#index', as: 'import'

  resources :sessions
  resources :users

  root to: 'creatives#index'
end

app/models/triplace.rb
class Triplace < ApplicationRecord
  belongs_to :city

  def self.import(file)
    CSV.foreach(file.path, :headers => true) do |row|
      Triplace.create! row.to_h
    end
  end
end

app/controllers/triplaces_controller.rb
class TriplacesController < ApplicationController
  before_action :set_triplace, only: [:show, :edit, :update, :destroy]

  def import
    Triplace.import(params[:file])
    redirect_to root_url, notice: "Products imported"
  end   
  # GET /triplaces
  # GET /triplaces.json
  def index
    @user = User.find(params[:id])
    @triplaces = Triplace.all
  end

  # GET /triplaces/1
  # GET /triplaces/1.json
  def show
  end

  # GET /triplaces/new
  def new
    @triplace = Triplace.new
  end

  # GET /triplaces/1/edit
  def edit
  end

  # POST /triplaces
  # POST /triplaces.json
  def create
    @triplace = Triplace.new(triplace_params)

    respond_to do |format|
      if @triplace.save
        format.html { redirect_to @triplace, notice: 'Triplace was successfully created.' }
        format.json { render :show, status: :created, location: @triplace }
      else
        format.html { render :new }
        format.json { render json: @triplace.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /triplaces/1
  # PATCH/PUT /triplaces/1.json
  def update
    respond_to do |format|
      if @triplace.update(triplace_params)
        format.html { redirect_to @triplace, notice: 'Triplace was successfully updated.' }
        format.json { render :show, status: :ok, location: @triplace }
      else
        format.html { render :edit }
        format.json { render json: @triplace.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /triplaces/1
  # DELETE /triplaces/1.json
  def destroy
    @triplace.destroy
    respond_to do |format|
      format.html { redirect_to triplaces_url, notice: 'Triplace was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_triplace
      @triplace = Triplace.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def triplace_params
      params.fetch(:triplace, {})
    end 
end

app/helpers/triplaces_helper.rb
module TriplacesHelper
end

app/views/triplaces/_form.html.erb
<%= form_with(model: triplace, local: true) do |form| %>
  <% if triplace.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(triplace.errors.count, "error") %> prohibited this triplace from being saved:</h2>

      <ul>
      <% triplace.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/triplaces/edit.html.erb
<h1>Editing Triplace</h1>

<%= render 'form', triplace: @triplace %>

<%= link_to 'Show', @triplace %> |
<%= link_to 'Back', triplaces_path %>

app/views/triplaces/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Triplaces</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @triplaces.each do |triplace| %>
      <tr>
        <td><%= link_to 'Show', triplace %></td>
        <td><%= link_to 'Edit', edit_triplace_path(triplace) %></td>
        <td><%= link_to 'Destroy', triplace, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Triplace', new_triplace_path %>

app/views/triplaces/new.html.erb
<h1>New Triplace</h1>

<%= render 'form', triplace: @triplace %>

<%= link_to 'Back', triplaces_path %>

app/views/triplaces/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_triplace_path(@triplace) %> |
<%= link_to 'Back', triplaces_path %>