config/routes.rb
Rails.application.routes.draw do

  get 'supported_cities/index'

  get 'attraction_info/index'

  get 'import/index'

  resources :triplaces do
    collection {post :import}
  end
  resources :cities

  resources :schedules

  # cities api routes
  get 'data/cities'
  get 'data/city/:id', to: 'data#city'

  # attraction api routes
  get 'data/attraction/:id', to: 'data#attraction'

  # city page routes
  get 'city_detail/:id', to: 'city_detail#index'

  # attraction page routes
  get 'attraction_detail/:id', to: 'attraction_info#index'

  # generate schedule routes
  get 'generate_schedule/city/:city_id/days/:days', to: 'generate_schedule#no_budget'
  get 'generate_schedule/city/:city_id/days/:days/budget/:budget', to: 'generate_schedule#budget'

  # schedules routes
  get 'schedules/city/:city_id/days/:days/budget/:budget', to: 'schedules#index'
  get 'schedules/:id', to: 'schedules#show'

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'add', to: 'cities#new', as: 'add'
  get 'import', to: 'import#index', as: 'import'

  resources :sessions
  resources :users

  root to: 'creatives#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  has_many :tripplaces, dependent: :destroy
end

app/models/schedule.rb
class Schedule < ApplicationRecord
  belongs_to :user
end

app/models/triplace.rb
class Triplace < ApplicationRecord
  belongs_to :city

  def self.import(file)
    CSV.foreach(file.path, :headers => true) do |row|
      Triplace.create! row.to_h
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :schedules

  before_save {self.email = email.downcase}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum: 255},
            format: {with: VALID_EMAIL_REGEX},
            uniqueness: {case_sensitive: false}
  has_secure_password
  validates_uniqueness_of :email
  validates_uniqueness_of :username
  validates_presence_of :username, :email, :password
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  before_action :set_city, only: [:show, :edit, :update, :destroy]

  # GET /cities
  # GET /cities.json
  def index
    @cities = City.all
  end

  # GET /cities/1
  # GET /cities/1.json
  def show
  end

  # GET /cities/new
  def new
    @city = City.new
    if current_user
      @user=User.find(current_user.id)
    else
      @user=nil
    end
  end

  # GET /cities/1/edit
  def edit
  end

  # POST /cities
  # POST /cities.json
  def create
    @city = City.new(city_params)
    respond_to do |format|
      if @city.save
        format.html {redirect_to import_index_url, notice: 'City was successfully created.'}
        format.json {render :show, status: :created, location: @city}
      else
        format.html {render :new}
        format.json {render json: @city.errors, status: :unprocessable_entity}
      end
    end
  end

  # PATCH/PUT /cities/1
  # PATCH/PUT /cities/1.json
  def update
    respond_to do |format|
      if @city.update(city_params)
        format.html {redirect_to @city, notice: 'City was successfully updated.'}
        format.json {render :show, status: :ok, location: @city}
      else
        format.html {render :edit}
        format.json {render json: @city.errors, status: :unprocessable_entity}
      end
    end
  end

  # DELETE /cities/1
  # DELETE /cities/1.json
  def destroy
    @city.destroy
    respond_to do |format|
      format.html {redirect_to cities_url, notice: 'City was successfully destroyed.'}
      format.json {head :no_content}
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_city
    @city = City.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def city_params
    params.require(:city).permit(:name, :country, :photoURL)
  end
end

app/controllers/creatives_controller.rb
class CreativesController < ApplicationController
  layout "creative"
  def index
        if(current_user)    
	@user=User.find(current_user.id)
        else
        @user=nil
	end  
	end
	end

app/controllers/data_controller.rb
class DataController < ApplicationController

  def cities
    cities = City.all
    if cities.empty?
      render json: {status: 'FAILURE', message: 'No cities found', data: cities}, status: :ok
    else
      render json: {status: 'SUCCESS', message: 'Loaded all cities', data: cities}, status: :ok
    end
  end

  def city
    attractions = Triplace.where(city_id: params[:id])
    city_name = City.find(params[:id]).name
    country_name = City.find(params[:id]).country
    if attractions.empty?
      render json: {status: 'FAILURE', message: 'No attractions found / City does not exist', data: attractions}, status: :ok
    else
      render json: {status: 'SUCCESS', message: 'Loaded all attractions', city_name: city_name, country_name: country_name,
                    data: attractions } , status: :ok
    end
  end

  def attraction
    attraction = Triplace.where(id: params[:id])
    if attraction.empty?
      render json: {status: 'FAILURE', message: 'Attraction not found', data: attraction}, status: :ok
    else
      render json: {status: 'SUCCESS', message: 'Loaded attraction', data: attraction}, status: :ok
    end
  end

end

app/controllers/import_controller.rb
class ImportController < ApplicationController
  def index
  	@triplace = Triplace.order(:title)
        if current_user
           @user=User.find(current_user.id)
        	
        else
        	@user=nil
        end	
  	
  end	
end  

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  layout "creative"

  def index
  end

  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: "Logged in"

    else
      flash.now.alert = "Email or password is invalid"
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Logged out"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def index
    @user = User.find(current_user.id)
    if @user.isAdmin
      @users = User.all
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "Welcome to Savecation!!"
      redirect_to user_url(@user.id)

    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
    if @user.isAdmin
      @users = User.all
    end

    @schedules = @user.schedules
    puts @schedules
  end

  def destroy
    @user=User.find(params[:id])
    @user.destroy
    respond_to do |format|
      format.html {redirect_to users_url, notice: 'User was successfully destroyed.'}
      format.json {head :no_content}
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :username, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attraction_info_helper.rb
module AttractionInfoHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/city_detail_helper.rb
module CityDetailHelper
end

app/helpers/data_helper.rb
module DataHelper
end

app/helpers/import_helper.rb
module ImportHelper
end

app/helpers/schedules_helper.rb
module SchedulesHelper

  def trim(num)
    i, f = num.to_i, num.to_f
    i == f ? i : f
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/triplaces_helper.rb
module TriplacesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/creatives/_bg_primary.html.erb
<section class="bg-primary" id="about">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-lg-offset-2 text-center">
        <h2 class="section-heading">We've got what you need!</h2>
        <hr class="light">
        <p class="text-faded">Our main focus is to help you choose which tourist
          attractions to visit and restaurants to go to based on your budget.</p>
        <!--<a href="#" class="btn btn-default btn-xl">Sign Up!</a>-->
        <%= link_to "Sign Up", signup_path, :class => "btn btn-default btn-xl" %>
      </div>
    </div>
  </div>
</section>

app/views/creatives/_call_to_action.html.erb
<aside class="bg-dark">
  <div class="container text-center">
    <div class="call-to-action">
      <h2>Free Download at Start Bootstrap!</h2>
      <a href="#" class="btn btn-default btn-xl wow tada">Download Now!</a>
    </div>
  </div>
</aside>

app/views/creatives/_contact.html.erb
<section id="contact">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-lg-offset-2 text-center">
        <h2 class="section-heading">Let's Get In Touch!</h2>
        <hr class="primary">

      </div>
      <div class="col-lg-4 col-lg-offset-2 text-center">
        <i class="fa fa-phone fa-3x wow bounceIn"></i>
        <p>778-782-3111</p>
      </div>
      <div class="col-lg-4 text-center">
        <i class="fa fa-envelope-o fa-3x wow bounceIn" data-wow-delay=".1s"></i>
        <p><a href="mailto:admin@sfu.ca">admin@savecation.ca</a></p>
      </div>
    </div>
  </div>
</section>

app/views/creatives/_header.html.erb
<header>
  <div class="header-content">
    <div class="header-content-inner">
      <h1>Savecation</h1>
      <br><br><br>
      <p>Savecation is an online app that allows users to vacation on a budget.</p><br>
       <div class="wrap">
        <div class="search">
          <input type="text" autocomplete="off" id="search_term" list="json-citylist" class="searchTerm" placeholder="Enter your destination...">
          <datalist id="json-citylist"></datalist>
          <button onclick="search()" type="submit" class="searchButton">
            <i class="fa fa-search"></i>
          </button>
        </div>
        <kbd class="bg-dark" id="errorm"></kbd>
      </div>


      <script type="text/javascript">
          var dataList = document.getElementById('json-citylist');
          var input = document.getElementById('ajax');


          /**
           * @return {string}
           */
          function Get() {
              var Httpreq = new XMLHttpRequest(); // a new request
              Httpreq.open("GET", "https://pure-coast-27115.herokuapp.com/data/cities", false);
              Httpreq.send(null);
              return Httpreq.responseText;
          }

          var json_obj = JSON.parse(Get());
          data = json_obj["data"];
          var dict = {};

          for (var i = 0; i < data.length; i++) {
              var option = document.createElement('option');
              option.value = data[i].name;
              dataList.appendChild(option);
              dict[data[i].name.toLowerCase()] = "https://pure-coast-27115.herokuapp.com/city_detail/" + data[i].id;
          }

          function search() {
              var input = document.getElementById("search_term").value.toLowerCase();
              console.log(input);
              var keys = Object.keys(dict);
              var found = false;
              keys.forEach(function (key) {
                  if (key === input) {
                      found = true;
                      console.log("found in key input =" + found);
                      window.location = dict[key];
                  }
                  document.getElementById("errorm").innerHTML = "";
              });

              console.log("found =" + found);
              if (found === false) {
                  document.getElementById("errorm").innerHTML = "City spelled wrong or not yet supported";
              }
          }

          $("#search_term").on('keyup', function (e) {
              document.getElementById("errorm").innerHTML = "";
              if (e.keyCode === 13) {
                  search();
              }
          });




      </script>




    </div>

  </div>
</header>

app/views/creatives/_navbar.html.erb
<nav id="mainNav" class="navbar navbar-default">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <!--<a class="navbar-brand page-scroll" href="#page-top">Savecation</a>-->
      <%= link_to "Savecation", root_url, :class => "navbar-brand page-scroll" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li>
          <%= link_to "Home", root_path %>
        </li>
        <% if @user!=nil && @user.isAdmin %>

            <li>
              <%= link_to "Profile page", user_url(current_user.id) %>
            </li>
            <li>
              <%= link_to "Log Out", logout_path %>
            </li>
            <li>
              <%= link_to "Add", add_path(current_user.id) %>
            </li>
            <li>
              <%= link_to "Import", import_path(current_user.id) %>
            </li>
            <li>
              <%= link_to "Admin Page", users_path(current_user.id) %>
            </li>
        <% elsif current_user %>
            <li>
              <%= link_to "Profile page", user_url(current_user.id) %>
            </li>
            <li>
              <%= link_to "Log Out", logout_path %>
            </li>
        <% else %>
            <li>
              <%= link_to "Log In", login_path %>
            </li>
            <li>
              <%= link_to "Sign Up", signup_path %>
            </li>
        <% end %>
      </ul>
    </div>
    <!-- /.navbar-collapse -->
  </div>
  <!-- /.container-fluid -->
</nav>

app/views/creatives/_portfolio.html.erb
<section class="no-padding" id="portfolio">
  <div class="container-fluid">
    <div class="row no-gutter">
      <div class="col-lg-4 col-sm-6">
        <a href="http://pure-coast-27115.herokuapp.com/city_detail/1" class="portfolio-box">
          <%= image_tag "creative/portfolio/1.jpg", class: "img-responsive", alt: "" %>
          <div class="portfolio-box-caption">
            <div class="portfolio-box-caption-content">
              <!--<div class="project-category text-faded">
                  Category
              </div>-->
              <div class="project-name">
                Vancouver
              </div>
            </div>
          </div>
        </a>
      </div>
      <div class="col-lg-4 col-sm-6">
        <a href="http://pure-coast-27115.herokuapp.com/city_detail/2" class="portfolio-box">
          <%= image_tag "creative/portfolio/2.jpg", class: "img-responsive", alt: "" %>
          <div class="portfolio-box-caption">
            <div class="portfolio-box-caption-content">
              <!--<div class="project-category text-faded">
                  Category
              </div>-->
              <div class="project-name">
                Victoria
              </div>
            </div>
          </div>
        </a>
      </div>
      <div class="col-lg-4 col-sm-6">
        <a href="http://pure-coast-27115.herokuapp.com/city_detail/3" class="portfolio-box">
          <%= image_tag "creative/portfolio/3.jpg", class: "img-responsive", alt: "" %>
          <div class="portfolio-box-caption">
            <div class="portfolio-box-caption-content">
              <!--<div class="project-category text-faded">
                  Category
              </div>-->
              <div class="project-name">
                Rio de Janeiro
              </div>
            </div>
          </div>
        </a>
      </div>
      <div class="col-lg-4 col-sm-6">
        <a href="http://pure-coast-27115.herokuapp.com/city_detail/4" class="portfolio-box">
          <%= image_tag "creative/portfolio/4.jpg", class: "img-responsive", alt: "" %>
          <div class="portfolio-box-caption">
            <div class="portfolio-box-caption-content">
              <!--<div class="project-category text-faded">
                  Category
              </div>-->
              <div class="project-name">
                Taipei
              </div>
            </div>
          </div>
        </a>
      </div>
      <div class="col-lg-4 col-sm-6">
        <a href="http://pure-coast-27115.herokuapp.com/city_detail/5" class="portfolio-box">
          <%= image_tag "creative/portfolio/5.jpg", class: "img-responsive", alt: "" %>
          <div class="portfolio-box-caption">
            <div class="portfolio-box-caption-content">
              <!--<div class="project-category text-faded">
                  Category
              </div>-->
              <div class="project-name">
                Sydney
              </div>
            </div>
          </div>
        </a>
      </div>
      <div class="col-lg-4 col-sm-6">
        <a href="http://pure-coast-27115.herokuapp.com/city_detail/6" class="portfolio-box">
          <%= image_tag "creative/portfolio/6.jpg", class: "img-responsive", alt: "" %>
          <div class="portfolio-box-caption">
            <div class="portfolio-box-caption-content">
              <!--<div class="project-category text-faded">
                  Category
              </div>-->
              <div class="project-name">
                Amsterdam
              </div>
            </div>
          </div>
        </a>
      </div>
    </div>
  </div>
</section>

app/views/creatives/_services.html.erb
<section id="services">
  <div class="container">
    <div class="row">
      <div class="col-lg-12 text-center">
        <h2 class="section-heading">Most Popular Destinations</h2>
        <hr class="primary">
        <a href="http://pure-coast-27115.herokuapp.com/supported_cities/index" class="btn btn-primary btn-xl page-scroll">View all supported cities</a>
      </div>
    </div>
  </div>

</section>

app/views/creatives/index.html.erb
<%= render 'navbar' %>
<%= render 'header' %>
<% if @user==nil %>
    <%= render 'bg_primary' %>
<% end %>
<%= render 'services' %>
<%= render 'portfolio' %>
<!--<%= render 'call_to_action' %>-->
<%= render 'contact' %>